import { Handshake,  Mail, Pill,House, UserRoundCheck, UsersRound ,NotebookPen} from "lucide-react";

export const residents = [
  {
    name: "John Doe",
    dateOfBirth: new Date("1945-03-12"),
    roomNumber: 101,
    nextOfKin: "Jane Doe",
    photo: "https://randomuser.me/api/portraits/men/1.jpg",
    gender: "MALE",
    unitId: "unit-1",
  },
  {
    name: "Mary Smith",
    dateOfBirth: new Date("1939-06-28"),
    roomNumber: 102,
    nextOfKin: "Linda Smith",
    photo: "https://randomuser.me/api/portraits/women/2.jpg",
    gender: "FEMALE",
    unitId: "unit-1",
  },
  {
    name: "Robert Johnson",
    dateOfBirth: new Date("1942-11-05"),
    roomNumber: 103,
    nextOfKin: "Emily Johnson",
    photo: "https://randomuser.me/api/portraits/men/3.jpg",
    gender: "MALE",
    unitId: "unit-2",
  },
  {
    name: "Patricia Brown",
    dateOfBirth: new Date("1947-01-18"),
    roomNumber: 104,
    nextOfKin: "George Brown",
    photo: "https://randomuser.me/api/portraits/women/4.jpg",
    gender: "FEMALE",
    unitId: "unit-2",
  },
  {
    name: "Michael Davis",
    dateOfBirth: new Date("1940-04-09"),
    roomNumber: 105,
    nextOfKin: "Nancy Davis",
    photo: "https://randomuser.me/api/portraits/men/5.jpg",
    gender: "MALE",
    unitId: "unit-3",
  },
  {
    name: "Linda Martinez",
    dateOfBirth: new Date("1936-09-14"),
    roomNumber: 106,
    nextOfKin: "Kevin Martinez",
    photo: "https://randomuser.me/api/portraits/women/6.jpg",
    gender: "FEMALE",
    unitId: "unit-3",
  },
  {
    name: "William Garcia",
    dateOfBirth: new Date("1943-07-22"),
    roomNumber: 107,
    nextOfKin: "Anna Garcia",
    photo: "https://randomuser.me/api/portraits/men/7.jpg",
    gender: "MALE",
    unitId: "unit-4",
  },
  {
    name: "Barbara Wilson",
    dateOfBirth: new Date("1937-12-03"),
    roomNumber: 108,
    nextOfKin: "Thomas Wilson",
    photo: "https://randomuser.me/api/portraits/women/8.jpg",
    gender: "FEMALE",
    unitId: "unit-4",
  },
  {
    name: "James Taylor",
    dateOfBirth: new Date("1941-08-15"),
    roomNumber: 109,
    nextOfKin: "Laura Taylor",
    photo: "https://randomuser.me/api/portraits/men/9.jpg",
    gender: "MALE",
    unitId: "unit-5",
  },
  {
    name: "Susan Anderson",
    dateOfBirth: new Date("1946-05-30"),
    roomNumber: 110,
    nextOfKin: "Rachel Anderson",
    photo: "https://randomuser.me/api/portraits/women/10.jpg",
    gender: "FEMALE",
    unitId: "unit-5",
  },
];

  export const incidentData = [
    {
      id: "1",
      photo: "https://randomuser.me/api/portraits/women/21.jpg",
      name: "Alice Mathews",
      incidentNature: "Fall in bathroom",
      date: "2025-04-20",
      house: "Rose Villa"
    },
    {
      id: "2",
      photo: "https://randomuser.me/api/portraits/men/35.jpg",
      name: "George Brown",
      incidentNature: "Missed medication",
      date: "2025-04-21",
      house: "Maple Cottage"
    },
    {
      id: "3",
      photo: "https://randomuser.me/api/portraits/women/42.jpg",
      name: "Margaret Smith",
      incidentNature: "Aggressive behavior",
      date: "2025-04-19",
      house: "Willow House"
    },
    {
      id: "4",
      photo: "https://randomuser.me/api/portraits/men/41.jpg",
      name: "Albert White",
      incidentNature: "Wandering at night",
      date: "2025-04-18",
      house: "Rose Villa"
    },
    {
      id: "5",
      photo: "https://randomuser.me/api/portraits/women/37.jpg",
      name: "Dorothy Williams",
      incidentNature: "Refused food",
      date: "2025-04-22",
      house: "Maple Cottage"
    }
  ];
  export const items = [
    {
      title: "Home",
      url: "/user",
      icon: House,
    },
    {
      title: "Resident",
      url: "/list/resident",
      icon: UsersRound,
    },
    {
      title: "Staff",
      url: "/list/staff",
      icon: UserRoundCheck,
    },
    {
      title: "Handover",
      url: "/list/handover",
      icon: Handshake,
    },
    {
      title: "Medication",
      url: "/list/medication",
      icon: Pill,
    },
    
    {
      title: "Appoinments",
      url: "/list/appoinments",
      icon:NotebookPen,
    },
    {
      title: "Messages",
      url: "/list/messages",
      icon: Mail,
    },
    {
      title: "All Houses",
      url: "/list/houses",
      icon: House,
    }
    
  ];
  export const houses= [{name:"All Houses"},{name:"Rose"}, {name:"Comgal"}, {name:"Betheny"}]
  
  export const houseList=[
    {name:"Rose",Residents:1,staff:20}, {name:"Comgal",Residents:1,staff:20}, {name:"Betheny",Residents:1,staff:20},
  ]
  
 export const userManager = {
    id: "a1b2c3d4-e5f6-7890-abcd-1234567890ef",
    firstName: "Abi",
    lastName: "George",
    role: "manager",
    house:"ceridwen",
    photo: "https://randomuser.me/api/portraits/men/32.jpg", // or null if optional
  };
  
  export const userTeamlead = {
    id: "a1b2c3d4-e5f6-7890-abcd-1234567890ef",
    firstName: "Aaron",
    lastName: "Stokes",
    role: "teamleader",
    photo: "https://randomuser.me/api/portraits/men/33.jpg", 
    house:"ceridwen"
  };
  export const staff = [
    {
      name: "Alice Johnson",
      gender: "FEMALE",
      email: "alice.johnson@example.com",
      password: "hashedpassword1", // Replace with hashed version
      mobile: 7011123456,
      role: "teamLead",
      photo: "https://randomuser.me/api/portraits/women/10.jpg",
      unitId: "Ceridwen",
    },
    {
      name: "Daniel Smith",
      gender: "MALE",
      email: "daniel.smith@example.com",
      password: "hashedpassword2",
      mobile: 7011123457,
      role: "supportWorker",
      photo: "https://randomuser.me/api/portraits/men/11.jpg",
      gende: "MALE",
      unitId: "Comgal",
    },
    {
      name: "Olivia Brown",
      gender: "FEMALE",
      email: "olivia.brown@example.com",
      password: "hashedpassword3",
      mobile: 7011123458,
      role: "supportWorker",
      photo: "https://randomuser.me/api/portraits/women/12.jpg",
      gende: "FEMALE",
      unitId: "Bethany",
    },
    {
      name: "Liam Wilson",
      gender: "MALE",
      email: "liam.wilson@example.com",
      password: "hashedpassword4",
      mobile: 7011123459,
      role: "teamLead",
      photo: "https://randomuser.me/api/portraits/men/13.jpg",
      gende: "MALE",
      unitId: "Betheny",
    },
    {
      name: "Sophia Davis",
      gender: "FEMALE",
      email: "sophia.davis@example.com",
      password: "hashedpassword5",
      mobile: 7011123460,
      role: "supportWorker",
      photo: "https://randomuser.me/api/portraits/women/14.jpg",
      gende: "FEMALE",
      unitId: "Comgal",
    },
    {
      name: "Noah Taylor",
      gender: "MALE",
      email: "noah.taylor@example.com",
      password: "hashedpassword6",
      mobile: 7011123461,
      role: "supportWorker",
      photo: "https://randomuser.me/api/portraits/men/15.jpg",
      gende: "MALE",
      unitId: "Ceridwen",
    },
    {
      name: "Emily Moore",
      gender: "FEMALE",
      email: "emily.moore@example.com",
      password: "hashedpassword7",
      mobile: 7011123462,
      role: "teamLead",
      photo: "https://randomuser.me/api/portraits/women/16.jpg",
      gende: "FEMALE",
      unitId: "Betheny",
    },
    {
      name: "Benjn Clark",
      gender: "MALE",
      email: "benjamin.clark@example.com",
      password: "hashedpassword8",
      mobile: 7011123463,
      role: "supportWorker",
      photo: "https://randomuser.me/api/portraits/men/17.jpg",
      gende: "MALE",
      unitId: "Ceridwen",
    },
    {
      name: "Grace Lewis",
      gender: "FEMALE",
      email: "grace.lewis@example.com",
      password: "hashedpassword9",
      mobile: 7011123464,
      role: "supportWorker",
      photo: "https://randomuser.me/api/portraits/women/18.jpg",
      gende: "FEMALE",
      unitId: "Comgal",
    }]
    export const appointments = [
      {
        id: "1a1a1a1a-aaaa-1111-aaaa-111111111111",
        where: "Royal Victoria Hospital",
        date: new Date("2025-05-01T10:00:00Z"),
        time: new Date("2025-05-01T10:30:00Z"),
        with: "Dr. Susan Smith",
        avatar: "https://randomuser.me/api/portraits/women/44.jpg",
        residentId: "Clara Mcd",
        unitId: "Comgal",
      },
      {
        id: "2b2b2b2b-bbbb-2222-bbbb-222222222222",
        where: "Dental Care Centre",
        date: new Date("2025-05-03T09:00:00Z"),
        time: new Date("2025-05-03T09:45:00Z"),
        with: "Dr. Alan Jones",
        avatar: "https://randomuser.me/api/portraits/men/32.jpg",
        residentId: "Ben Chris",
        unitId: "Ceridwen",
      },
      {
        id: "3c3c3c3c-cccc-3333-cccc-333333333333",
        where: "Eye Clinic",
        date: new Date("2025-05-05T14:00:00Z"),
        time: new Date("2025-05-05T14:30:00Z"),
        with: "Dr. Rachel Lee",
        avatar: "https://randomuser.me/api/portraits/women/68.jpg",
        residentId: "Moore Gaue",
        unitId: "Betheny",
      },
      {
        id: "4d4d4d4d-dddd-4444-dddd-444444444444",
        where: "GP Clinic",
        date: new Date("2025-05-07T11:00:00Z"),
        time: new Date("2025-05-07T11:20:00Z"),
        with: "Dr. Michael Green",
        avatar: "https://randomuser.me/api/portraits/men/74.jpg",
        residentId: "Aark Musds",
        unitId: "Betheny",
      },
      {
        id: "5e5e5e5e-eeee-5555-eeee-555555555555",
        where: "Cardiology Department",
        date: new Date("2025-05-10T08:30:00Z"),
        time: new Date("2025-05-10T09:00:00Z"),
        with: "Dr. Anna Patel",
        avatar: "https://randomuser.me/api/portraits/women/22.jpg",
        residentId: "Mathew Mackl",
        unitId: "Samaria",
      },
      {
          id: "5e5e5e5e-eeee-5555-eeee-555555555555",
          where: "Cardiology Department",
          date: new Date("2025-05-10T08:30:00Z"),
          time: new Date("2025-05-10T09:00:00Z"),
          with: "Dr. Anna Patel",
          avatar: "https://randomuser.me/api/portraits/women/22.jpg",
          residentId: "Zara Zakaria",
          unitId: "Samaria",
        },
      {
          id: "5e5e5e5e-eeee-5555-eeee-555555555555",
          where: "Cardiology Department",
          date: new Date("2025-05-10T08:30:00Z"),
          time: new Date("2025-05-10T09:00:00Z"),
          with: "Dr. Anna Patel",
          avatar: "https://randomuser.me/api/portraits/women/22.jpg",
          residentId: "Zara Zakaria",
          unitId: "Samaria",
        },
      {
          id: "5e5e5e5e-eeee-5555-eeee-555555555555",
          where: "Cardiology Department",
          date: new Date("2025-05-10T08:30:00Z"),
          time: new Date("2025-05-10T09:00:00Z"),
          with: "Dr. Anna Patel",
          avatar: "https://randomuser.me/api/portraits/women/22.jpg",
          residentId: "Zara Zakaria",
          unitId: "Samaria",
        },
      {
          id: "5e5e5e5e-eeee-5555-eeee-555555555555",
          where: "Cardiology Department",
          date: new Date("2025-05-10T08:30:00Z"),
          time: new Date("2025-05-10T09:00:00Z"),
          with: "Dr. Anna Patel",
          avatar: "https://randomuser.me/api/portraits/women/22.jpg",
          residentId: "Zara Zakaria",
          unitId: "Samaria",
        },
      {
          id: "5e5e5e5e-eeee-5555-eeee-555555555555",
          where: "Cardiology Department",
          date: new Date("2025-05-10T08:30:00Z"),
          time: new Date("2025-05-10T09:00:00Z"),
          with: "Dr. Anna Patel",
          avatar: "https://randomuser.me/api/portraits/women/22.jpg",
          residentId: "Zara Zakaria",
          unitId: "Samaria",
        },
      {
          id: "5e5e5e5e-eeee-5555-eeee-555555555555",
          where: "Cardiology Department",
          date: new Date("2025-05-10T08:30:00Z"),
          time: new Date("2025-05-10T09:00:00Z"),
          with: "Dr. Anna Patel",
          avatar: "https://randomuser.me/api/portraits/women/22.jpg",
          residentId: "Zara Zakaria",
          unitId: "Samaria",
        },
      {
          id: "5e5e5e5e-eeee-5555-eeee-555555555555",
          where: "Cardiology Department",
          date: new Date("2025-05-10T08:30:00Z"),
          time: new Date("2025-05-10T09:00:00Z"),
          with: "Dr. Anna Patel",
          avatar: "https://randomuser.me/api/portraits/women/22.jpg",
          residentId: "Zara Zakaria",
          unitId: "Samaria",
        },
      {
          id: "5e5e5e5e-eeee-5555-eeee-555555555555",
          where: "Cardiology Department",
          date: new Date("2025-05-10T08:30:00Z"),
          time: new Date("2025-05-10T09:00:00Z"),
          with: "Dr. Anna Patel",
          avatar: "https://randomuser.me/api/portraits/women/22.jpg",
          residentId: "Zara Zakaria",
          unitId: "Samaria",
        },
      {
          id: "5e5e5e5e-eeee-5555-eeee-555555555555",
          where: "Cardiology Department",
          date: new Date("2025-05-10T08:30:00Z"),
          time: new Date("2025-05-10T09:00:00Z"),
          with: "Dr. Anna Patel",
          avatar: "https://randomuser.me/api/portraits/women/22.jpg",
          residentId: "Zara Zakaria",
          unitId: "Samaria",
        },
      {
          id: "5e5e5e5e-eeee-5555-eeee-555555555555",
          where: "Cardiology Department",
          date: new Date("2025-05-10T08:30:00Z"),
          time: new Date("2025-05-10T09:00:00Z"),
          with: "Dr. Anna Patel",
          avatar: "https://randomuser.me/api/portraits/women/22.jpg",
          residentId: "Zara Zakaria",
          unitId: "Samaria",
        },
      {
          id: "5e5e5e5e-eeee-5555-eeee-555555555555",
          where: "Cardiology Department",
          date: new Date("2025-05-10T08:30:00Z"),
          time: new Date("2025-05-10T09:00:00Z"),
          with: "Dr. Anna Patel",
          avatar: "https://randomuser.me/api/portraits/women/22.jpg",
          residentId: "Zara Zakaria",
          unitId: "Samaria",
        },
      {
          id: "5e5e5e5e-eeee-5555-eeee-555555555555",
          where: "Cardiology Department",
          date: new Date("2025-05-10T08:30:00Z"),
          time: new Date("2025-05-10T09:00:00Z"),
          with: "Dr. Anna Patel",
          avatar: "https://randomuser.me/api/portraits/women/22.jpg",
          residentId: "Zara Zakaria",
          unitId: "Samaria",
        },
    ];
    