import { Handshake,  Mail, Pill,House, UserRoundCheck, UsersRound ,NotebookPen} from "lucide-react";

export const residents = [
    {
      id: "1d24bfae-1a2e-4cde-9e9d-a1f842b4f021",
      name: "Alice Mathews",
      dateOfBirth: "1942-08-15",
      roomNumber: 101,
      nextOfKin: "John Mathews",
      imge: "https://randomuser.me/api/portraits/women/21.jpg",
      unitId: "unit-001"
    },
    {
      id: "32fc86f7-348e-4e29-a3f2-4c8cfbe09a29",
      name: "George Brown",
      dateOfBirth: "1938-05-03",
      roomNumber: 102,
      nextOfKin: "Mary Brown",
      imge: "https://randomuser.me/api/portraits/men/35.jpg",
      unitId: "unit-001"
    },
    {
      id: "52c4b72d-51fd-4cfa-bff5-daa45de3eb29",
      name: "Margaret Smith",
      dateOfBirth: "1945-12-11",
      roomNumber: 103,
      nextOfKin: "Henry Smith",
      imge: "https://randomuser.me/api/portraits/women/42.jpg",
      unitId: "unit-002"
    },
    {
      id: "b1c2d79e-f214-4e68-9c26-cb0a48c99d63",
      name: "Albert White",
      dateOfBirth: "1939-02-22",
      roomNumber: 104,
      nextOfKin: "Ellen White",
      imge: "https://randomuser.me/api/portraits/men/41.jpg",
      unitId: "unit-002"
    },
    {
      id: "6c56c6f4-66e9-4664-93f5-502a1f1fbbaf",
      name: "Dorothy Williams",
      dateOfBirth: "1944-10-09",
      roomNumber: 105,
      nextOfKin: "Grace Williams",
      imge: "https://randomuser.me/api/portraits/women/37.jpg",
      unitId: "unit-003"
    },
    {
      id: "a5e05ef0-e805-4c80-938e-f58d463b2ac7",
      name: "Edward Johnson",
      dateOfBirth: "1941-07-18",
      roomNumber: 106,
      nextOfKin: "Sarah Johnson",
      imge: "https://randomuser.me/api/portraits/men/22.jpg",
      unitId: "unit-003"
    },
    {
      id: "7f812c36-1fcd-40b4-a50d-9d634d5b48a0",
      name: "Betty Harris",
      dateOfBirth: "1943-03-25",
      roomNumber: 107,
      nextOfKin: "Laura Harris",
      imge: "https://randomuser.me/api/portraits/women/50.jpg",
      unitId: "unit-004"
    },
    {
      id: "f3b19a67-4c72-41a4-8214-1ffcf126c3b3",
      name: "Frank Thompson",
      dateOfBirth: "1940-09-01",
      roomNumber: 108,
      nextOfKin: "Emma Thompson",
      imge: "https://randomuser.me/api/portraits/men/50.jpg",
      unitId: "unit-004"
    },
    {
      id: "9d8f6a53-114f-4892-81d7-d0740b2a828e",
      name: "Helen Walker",
      dateOfBirth: "1946-11-20",
      roomNumber: 109,
      nextOfKin: "Paul Walker",
      imge: "https://randomuser.me/api/portraits/women/12.jpg",
      unitId: "unit-005"
    },
    {
      id: "4a9d8b17-7f01-4e68-8b5b-6b2f9ef5a871",
      name: "Charles Lewis",
      dateOfBirth: "1937-06-30",
      roomNumber: 110,
      nextOfKin: "Rachel Lewis",
      imge: "https://randomuser.me/api/portraits/men/11.jpg",
      unitId: "unit-005"
    }
  ];
  export const incidentData = [
    {
      id: "1",
      photo: "https://randomuser.me/api/portraits/women/21.jpg",
      name: "Alice Mathews",
      incidentNature: "Fall in bathroom",
      date: "2025-04-20",
      house: "Rose Villa"
    },
    {
      id: "2",
      photo: "https://randomuser.me/api/portraits/men/35.jpg",
      name: "George Brown",
      incidentNature: "Missed medication",
      date: "2025-04-21",
      house: "Maple Cottage"
    },
    {
      id: "3",
      photo: "https://randomuser.me/api/portraits/women/42.jpg",
      name: "Margaret Smith",
      incidentNature: "Aggressive behavior",
      date: "2025-04-19",
      house: "Willow House"
    },
    {
      id: "4",
      photo: "https://randomuser.me/api/portraits/men/41.jpg",
      name: "Albert White",
      incidentNature: "Wandering at night",
      date: "2025-04-18",
      house: "Rose Villa"
    },
    {
      id: "5",
      photo: "https://randomuser.me/api/portraits/women/37.jpg",
      name: "Dorothy Williams",
      incidentNature: "Refused food",
      date: "2025-04-22",
      house: "Maple Cottage"
    }
  ];
  export const items = [
    {
      title: "Home",
      url: "/manager",
      icon: House,
    },
    {
      title: "Resident",
      url: "/list/resident",
      icon: UsersRound,
    },
    {
      title: "Staff",
      url: "/list/staff",
      icon: UserRoundCheck,
    },
    {
      title: "Handover",
      url: "/list/handover",
      icon: Handshake,
    },
    {
      title: "Medication",
      url: "/list/medication",
      icon: Pill,
    },
    
    {
      title: "Appoinments",
      url: "/list/appoinments",
      icon:NotebookPen,
    },
    {
      title: "Messages",
      url: "/list/messages",
      icon: Mail,
    },
    {
      title: "Houses",
      url: "/list/houses",
      icon: House,
    }
    
  ];
  export const houses= [{name:"All Houses"},{name:"ceridwen"}, {name:"comgal"}, {name:"betheny"}]
  
 export const userManager = {
    id: "a1b2c3d4-e5f6-7890-abcd-1234567890ef",
    firstName: "Abi",
    lastName: "George",
    role: "manager",
    house:"ceridwen",
    photo: "https://randomuser.me/api/portraits/men/32.jpg", // or null if optional
  };
  
  export const userTeamlead = {
    id: "a1b2c3d4-e5f6-7890-abcd-1234567890ef",
    firstName: "Aaron",
    lastName: "Stokes",
    role: "teamleader",
    photo: "https://randomuser.me/api/portraits/men/33.jpg", 
    house:"ceridwen"
  };
  export const staff = [
    {
      name: "Alice Johnson",
      gender: "FEMALE",
      email: "alice.johnson@example.com",
      password: "hashedpassword1", // Replace with hashed version
      mobile: 7011123456,
      role: "teamLead",
      photo: "https://randomuser.me/api/portraits/women/10.jpg",
      unitId: "Ceridwen",
    },
    {
      name: "Daniel Smith",
      gender: "MALE",
      email: "daniel.smith@example.com",
      password: "hashedpassword2",
      mobile: 7011123457,
      role: "supportWorker",
      photo: "https://randomuser.me/api/portraits/men/11.jpg",
      gende: "MALE",
      unitId: "Comgal",
    },
    {
      name: "Olivia Brown",
      gender: "FEMALE",
      email: "olivia.brown@example.com",
      password: "hashedpassword3",
      mobile: 7011123458,
      role: "supportWorker",
      photo: "https://randomuser.me/api/portraits/women/12.jpg",
      gende: "FEMALE",
      unitId: "Bethany",
    },
    {
      name: "Liam Wilson",
      gender: "MALE",
      email: "liam.wilson@example.com",
      password: "hashedpassword4",
      mobile: 7011123459,
      role: "teamLead",
      photo: "https://randomuser.me/api/portraits/men/13.jpg",
      gende: "MALE",
      unitId: "Betheny",
    },
    {
      name: "Sophia Davis",
      gender: "FEMALE",
      email: "sophia.davis@example.com",
      password: "hashedpassword5",
      mobile: 7011123460,
      role: "supportWorker",
      photo: "https://randomuser.me/api/portraits/women/14.jpg",
      gende: "FEMALE",
      unitId: "Comgal",
    },
    {
      name: "Noah Taylor",
      gender: "MALE",
      email: "noah.taylor@example.com",
      password: "hashedpassword6",
      mobile: 7011123461,
      role: "supportWorker",
      photo: "https://randomuser.me/api/portraits/men/15.jpg",
      gende: "MALE",
      unitId: "Ceridwen",
    },
    {
      name: "Emily Moore",
      gender: "FEMALE",
      email: "emily.moore@example.com",
      password: "hashedpassword7",
      mobile: 7011123462,
      role: "teamLead",
      photo: "https://randomuser.me/api/portraits/women/16.jpg",
      gende: "FEMALE",
      unitId: "Betheny",
    },
    {
      name: "Benjn Clark",
      gender: "MALE",
      email: "benjamin.clark@example.com",
      password: "hashedpassword8",
      mobile: 7011123463,
      role: "supportWorker",
      photo: "https://randomuser.me/api/portraits/men/17.jpg",
      gende: "MALE",
      unitId: "Ceridwen",
    },
    {
      name: "Grace Lewis",
      gender: "FEMALE",
      email: "grace.lewis@example.com",
      password: "hashedpassword9",
      mobile: 7011123464,
      role: "supportWorker",
      photo: "https://randomuser.me/api/portraits/women/18.jpg",
      gende: "FEMALE",
      unitId: "Comgal",
    }]
    export const appointments = [
      {
        id: "1a1a1a1a-aaaa-1111-aaaa-111111111111",
        where: "Royal Victoria Hospital",
        date: new Date("2025-05-01T10:00:00Z"),
        time: new Date("2025-05-01T10:30:00Z"),
        with: "Dr. Susan Smith",
        avatar: "https://randomuser.me/api/portraits/women/44.jpg",
        residentId: "Clara Mcd",
        unitId: "Comgal",
      },
      {
        id: "2b2b2b2b-bbbb-2222-bbbb-222222222222",
        where: "Dental Care Centre",
        date: new Date("2025-05-03T09:00:00Z"),
        time: new Date("2025-05-03T09:45:00Z"),
        with: "Dr. Alan Jones",
        avatar: "https://randomuser.me/api/portraits/men/32.jpg",
        residentId: "Ben Chris",
        unitId: "Ceridwen",
      },
      {
        id: "3c3c3c3c-cccc-3333-cccc-333333333333",
        where: "Eye Clinic",
        date: new Date("2025-05-05T14:00:00Z"),
        time: new Date("2025-05-05T14:30:00Z"),
        with: "Dr. Rachel Lee",
        avatar: "https://randomuser.me/api/portraits/women/68.jpg",
        residentId: "Moore Gaue",
        unitId: "Betheny",
      },
      {
        id: "4d4d4d4d-dddd-4444-dddd-444444444444",
        where: "GP Clinic",
        date: new Date("2025-05-07T11:00:00Z"),
        time: new Date("2025-05-07T11:20:00Z"),
        with: "Dr. Michael Green",
        avatar: "https://randomuser.me/api/portraits/men/74.jpg",
        residentId: "Aark Musds",
        unitId: "Betheny",
      },
      {
        id: "5e5e5e5e-eeee-5555-eeee-555555555555",
        where: "Cardiology Department",
        date: new Date("2025-05-10T08:30:00Z"),
        time: new Date("2025-05-10T09:00:00Z"),
        with: "Dr. Anna Patel",
        avatar: "https://randomuser.me/api/portraits/women/22.jpg",
        residentId: "Mathew Mackl",
        unitId: "Samaria",
      },
      {
          id: "5e5e5e5e-eeee-5555-eeee-555555555555",
          where: "Cardiology Department",
          date: new Date("2025-05-10T08:30:00Z"),
          time: new Date("2025-05-10T09:00:00Z"),
          with: "Dr. Anna Patel",
          avatar: "https://randomuser.me/api/portraits/women/22.jpg",
          residentId: "Zara Zakaria",
          unitId: "Samaria",
        },
      {
          id: "5e5e5e5e-eeee-5555-eeee-555555555555",
          where: "Cardiology Department",
          date: new Date("2025-05-10T08:30:00Z"),
          time: new Date("2025-05-10T09:00:00Z"),
          with: "Dr. Anna Patel",
          avatar: "https://randomuser.me/api/portraits/women/22.jpg",
          residentId: "Zara Zakaria",
          unitId: "Samaria",
        },
      {
          id: "5e5e5e5e-eeee-5555-eeee-555555555555",
          where: "Cardiology Department",
          date: new Date("2025-05-10T08:30:00Z"),
          time: new Date("2025-05-10T09:00:00Z"),
          with: "Dr. Anna Patel",
          avatar: "https://randomuser.me/api/portraits/women/22.jpg",
          residentId: "Zara Zakaria",
          unitId: "Samaria",
        },
      {
          id: "5e5e5e5e-eeee-5555-eeee-555555555555",
          where: "Cardiology Department",
          date: new Date("2025-05-10T08:30:00Z"),
          time: new Date("2025-05-10T09:00:00Z"),
          with: "Dr. Anna Patel",
          avatar: "https://randomuser.me/api/portraits/women/22.jpg",
          residentId: "Zara Zakaria",
          unitId: "Samaria",
        },
      {
          id: "5e5e5e5e-eeee-5555-eeee-555555555555",
          where: "Cardiology Department",
          date: new Date("2025-05-10T08:30:00Z"),
          time: new Date("2025-05-10T09:00:00Z"),
          with: "Dr. Anna Patel",
          avatar: "https://randomuser.me/api/portraits/women/22.jpg",
          residentId: "Zara Zakaria",
          unitId: "Samaria",
        },
      {
          id: "5e5e5e5e-eeee-5555-eeee-555555555555",
          where: "Cardiology Department",
          date: new Date("2025-05-10T08:30:00Z"),
          time: new Date("2025-05-10T09:00:00Z"),
          with: "Dr. Anna Patel",
          avatar: "https://randomuser.me/api/portraits/women/22.jpg",
          residentId: "Zara Zakaria",
          unitId: "Samaria",
        },
      {
          id: "5e5e5e5e-eeee-5555-eeee-555555555555",
          where: "Cardiology Department",
          date: new Date("2025-05-10T08:30:00Z"),
          time: new Date("2025-05-10T09:00:00Z"),
          with: "Dr. Anna Patel",
          avatar: "https://randomuser.me/api/portraits/women/22.jpg",
          residentId: "Zara Zakaria",
          unitId: "Samaria",
        },
      {
          id: "5e5e5e5e-eeee-5555-eeee-555555555555",
          where: "Cardiology Department",
          date: new Date("2025-05-10T08:30:00Z"),
          time: new Date("2025-05-10T09:00:00Z"),
          with: "Dr. Anna Patel",
          avatar: "https://randomuser.me/api/portraits/women/22.jpg",
          residentId: "Zara Zakaria",
          unitId: "Samaria",
        },
      {
          id: "5e5e5e5e-eeee-5555-eeee-555555555555",
          where: "Cardiology Department",
          date: new Date("2025-05-10T08:30:00Z"),
          time: new Date("2025-05-10T09:00:00Z"),
          with: "Dr. Anna Patel",
          avatar: "https://randomuser.me/api/portraits/women/22.jpg",
          residentId: "Zara Zakaria",
          unitId: "Samaria",
        },
      {
          id: "5e5e5e5e-eeee-5555-eeee-555555555555",
          where: "Cardiology Department",
          date: new Date("2025-05-10T08:30:00Z"),
          time: new Date("2025-05-10T09:00:00Z"),
          with: "Dr. Anna Patel",
          avatar: "https://randomuser.me/api/portraits/women/22.jpg",
          residentId: "Zara Zakaria",
          unitId: "Samaria",
        },
      {
          id: "5e5e5e5e-eeee-5555-eeee-555555555555",
          where: "Cardiology Department",
          date: new Date("2025-05-10T08:30:00Z"),
          time: new Date("2025-05-10T09:00:00Z"),
          with: "Dr. Anna Patel",
          avatar: "https://randomuser.me/api/portraits/women/22.jpg",
          residentId: "Zara Zakaria",
          unitId: "Samaria",
        },
      {
          id: "5e5e5e5e-eeee-5555-eeee-555555555555",
          where: "Cardiology Department",
          date: new Date("2025-05-10T08:30:00Z"),
          time: new Date("2025-05-10T09:00:00Z"),
          with: "Dr. Anna Patel",
          avatar: "https://randomuser.me/api/portraits/women/22.jpg",
          residentId: "Zara Zakaria",
          unitId: "Samaria",
        },
    ];
    